/*
 * Project: Outlays-dam
 * Author: Dominik Obłoza
 * User: @BLOCKYe
 * Date: 11.11.2022
 * Time: 23:29
*/

import type {NextPage} from 'next'
import Head from 'next/head'
import AnalyticsView from "../../client/modules/analytics/views/AnalyticsView";
import AuthMiddleware from "../../client/common/axios/authMiddleware";
import {useEffect} from "react";

const Analytics: NextPage = () => {

    useEffect(() => {
        AuthMiddleware.checkToken().then()
    }, [])

    return (
        <div>
            <Head>
                <title>Analityka - Outlays Dam - monitoruj swoje wydatki</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <AnalyticsView/>

        </div>
    )
}

export default Analytics
