-- AlterTable
ALTER TABLE "Goal" ALTER COLUMN "goalValue" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "reachedDate" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Operation" ALTER COLUMN "value" SET DATA TYPE DOUBLE PRECISION;
