version: '3.8'

services:
  app:
    image: 'outlays-dam-dev'
    build: .
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - app-node_modules:/app/node_modules
      - app-next:/app/.next

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgressql

volumes:
  db:
  app-node_modules:
  app-next:

