version: "3"

services:
  app:
    image: 'outlays-dam-dev'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: outlays
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgressql

volumes:
  db:

