/*
 * Project: Outlays-dam
 * Author: Dominik Obłoza
 * User: @BLOCKYe
 * Date: 15.08.2022
 * Time: 19:51
*/

import type {NextPage} from 'next'
import Head from 'next/head'
import {wrapper} from "../../client/common/redux/store";
import {fetchCategories} from "../../client/modules/categories/redux/CategoriesRepository";
import Paths from "../../client/common/router/paths";
import AuthMiddleware from "../../client/common/axios/authMiddleware";
import CategoriesView from "../../client/modules/categories/views/CategoriesView";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Kategorie - Outlays Dam - monitoruj swoje wydatki</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <CategoriesView/>

        </div>
    )
}

export const getServerSideProps = wrapper.getServerSideProps(
    (store) => async ({req, res}) => {
        const auth = await new AuthMiddleware(req, res).checkToken()

        if (!auth) {
            return {
                redirect: {
                    permanent: false,
                    destination: Paths.LOGIN
                }
            }
        }

        await store.dispatch(fetchCategories())

        return {
            props: {},
        };
    }
);

export default Home
