/*
 * Project: Outlays-dam
 * Author: Dominik Obłoza
 * User: @BLOCKYe
 * Date: 15.08.2022
 * Time: 19:51
*/

import type {NextPage} from 'next'
import Head from 'next/head'
import LoginView from "../../client/modules/users/views/LoginView";
import RegisterView from "../../client/modules/users/views/RegisterView";
import HomeView from "../../client/modules/outlays/views/HomeView";
import {wrapper} from "../../client/common/redux/store";
import {getCookie} from "cookies-next";
import {fetchUserProfile} from "../../client/modules/users/redux/UserRepository";
import axios from "axios";
import {fetchOutlays} from "../../client/modules/outlays/redux/OutlaysRepository";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Strona głowna - Outlays Dam - monitoruj swoje wydatki</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <HomeView />

        </div>
    )
}

export const getServerSideProps = wrapper.getServerSideProps(
    (store) => async ({req, res}) => {

        const token = getCookie('token', {req, res});
        await store.dispatch(fetchOutlays(token))
        await store.dispatch(fetchUserProfile(token))

        return {
            props: {},
        };
    }
);

export default Home
